### ISSUE TITLE
Code from problem 5 raise an error with imports from beginning of the file

### ISSUE THREAD

**Issue by swistak35** [janchorowski/nn_assignments#2]
In the beginning of the file there are "Standard IPython notebook imports". One of these imports is importing `print_function`, which makes old print syntax `print x` raise an error. However this older syntax is used in problem 5 snippets, so by default this code raise an error (fix is easy, just change print syntax used in problem 5 manually).

**Comment by alancucki** [comment]
Thanks, fixed.
